name: Pull Request Close
on:
  workflow_call:
    secrets:
        CI_ACTION_TOKEN:
          required: true


jobs:
    purge-image:
        name: Delete image from ghcr.io
        runs-on: ubuntu-latest
        steps:
          - uses: chipkent/action-cleanup-package@v1.0.1
            with:
              package-name: ${{ github.event.repository.name }}
              tag: pr-${{ github.event.pull_request.number }}
              github-token: ${{ secrets.CI_ACTION_TOKEN }}
    