name: Pre Pull Request Check Nodejs
on:
  workflow_call:
    inputs:
      VERSION_NUMBER:
        default: master
        type: string
      org_name:
        required: true
        type: string
    secrets:
      NODE_AUTH_TOKEN:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepr-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Create NPMRC
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> ~/.npmrc
          echo "@${{ inputs.org_name }}:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo 'registry "https://registry.yarnpkg.com"' >> ~/.yarnrc
      - name: yarn Install
        run: |
          yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Run tests
        if: always()
        run: |
          yarn test:cov
      - name: Coveralls
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info

      - name: Check is template repo
        id: check_template_repo
        uses: andstor/file-existence-action@v1
        with:
          files: '.template_repo'

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@${{ inputs.org_name }}'
      - name: Configure git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      # Publish to GitHub Packages
      - name: Publish to GitHub Packages - PR
        if: steps.check_template_repo.outputs.files_exists == 'false' && github.event_name == 'pull_request'
        run: yarn release --canary --preid pr${{ github.event.number }}bld${{ github.run_number }} --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Publish to GitHub Packages - Release
        if: steps.check_template_repo.outputs.files_exists == 'false' && github.event_name != 'pull_request'
        run: yarn release --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        # run: yarn release --create-release github --yes

  docker-build:
    name: Docker Build
    needs: [prepr-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check is template repo
        id: check_template_repo
        uses: andstor/file-existence-action@v1
        with:
          files: '.template_repo'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=${{ inputs.VERSION_NUMBER }} ,enable={{is_default_branch}}

          # tags: |
          #   # set latest tag for default branch
          #   type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Deployment YAML TMP
        uses: nowactions/envsubst@v1
        with:
          input: ./k8s/app-deployment.yaml
          output: ./app-deployment.yaml.tmp
        env:
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
      - name: Render Deployment YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./app-deployment.yaml.tmp
          output: ./k8s/app-deployment.yaml
        env:
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ steps.check_template_repo.outputs.files_exists == 'false' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "NODE_AUTH_TOKEN=${{ secrets.NODE_AUTH_TOKEN }}"
        env:
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
