name: Push To AKS
on:
  workflow_call:
    inputs:
      VERSION_NUMBER:
        default: master
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      resource_group:
        required: true
      cluster_name:
        required: true
      name_space:
        required: true
      deployment_location:
        required: false

jobs:
  push-aks:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1.4.3
        name: Azure login
        id: login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}'
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Render Deployment YAML TMP
        uses: nowactions/envsubst@v1
        with:
          input: ./k8s-prod/app-deployment.yaml
          output: ./app-deployment.yaml.tmp
        env:
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
      - name: Render Deployment YAML
        uses: nowactions/envsubst@v1
        with:
          input: ./app-deployment.yaml.tmp
          output: ./k8s-prod/app-deployment.yaml
        env:
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: '${{ secrets.name_space }}'
          manifests: |
            k8s-prod/*.yaml
        env:
          VERSION_NUMBER: ${{ inputs.VERSION_NUMBER }}
